"""Canonical lon/lat coordinates for the SWMM junctions in pune_base.inp.

pune_base.inp has no [COORDINATES] section, so this is the single source
of truth both the API's dry-network view and the terrain catchment
delineation key off of, instead of duplicating literals in each.

Generated by generate_network.py: 25 real intersections from
routing.py's road graph, farthest-point sampled for spatial spread, each
connected in pune_base.inp to its nearest downhill neighbor.
"""

JUNCTION_COORDINATES: dict[str, tuple[float, float]] = {
    "J00": (73.8414998, 18.5138464),
    "J01": (73.8376311, 18.5180517),
    "J02": (73.8461878, 18.5171692),
    "J03": (73.8465504, 18.5112539),
    "J04": (73.8376948, 18.5118848),
    "J05": (73.8415875, 18.5175742),
    "J06": (73.8434954, 18.5098794),
    "J07": (73.8447087, 18.5138185),
    "J08": (73.8391671, 18.5156369),
    "J09": (73.8434761, 18.5160188),
    "J10": (73.8441676, 18.51804),
    "J11": (73.8469163, 18.5138217),
    "J12": (73.83749, 18.513962),
    "J13": (73.8435971, 18.5119608),
    "J14": (73.8397044, 18.5127507),
    "J15": (73.8396603, 18.5178267),
    "J16": (73.8415203, 18.5157335),
    "J17": (73.8373094, 18.5158579),
    "J18": (73.8460238, 18.5153025),
    "J19": (73.8420168, 18.5112563),
    "J20": (73.8391719, 18.5141364),
    "J21": (73.8450707, 18.5114645),
    "J22": (73.842814, 18.5184017),
    "J23": (73.8385572, 18.516789),
    "J24": (73.8425066, 18.5149778),
}
